# Generated by Django 5.1.7 on 2025-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid to person1', 'Paid to Person1'), ('paid to person2', 'Paid to Person2')], max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('bill', models.FloatField()),
            ],
        ),
    ]
