# Generated by Django 5.1.7 on 2025-06-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_bill_alter_payment_date_time_and_more'),
    ]

    operations = [
    ]
