# Generated by Django 5.2.3 on 2025-06-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20250620_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid to person1', 'Paid to Nanu'), ('paid to person2', 'Paid to Lala')], max_length=20),
        ),
    ]
