# Generated by Django 5.2.3 on 2025-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.AddField(
            model_name='payment',
            name='item_name',
            field=models.CharField(choices=[('Aarav Sharma', 'Aarav Sharma'), ('Priya Patel', 'Priya Patel'), ('Rohan Singh', 'Rohan Singh'), ('Neha Gupta', 'Neha Gupta'), ('Vikram Desai', 'Vikram Desai'), ('Anjali Mehta', 'Anjali Mehta'), ('Karan Joshi', 'Karan Joshi'), ('Sneha Reddy', 'Sneha Reddy'), ('Arjun Kapoor', 'Arjun Kapoor'), ('Divya Nair', 'Divya Nair'), ('Sameer Khan', 'Sameer Khan'), ('Ritu Malhotra', 'Ritu Malhotra'), ('Amit Verma', 'Amit Verma'), ('Pooja Iyer', 'Pooja Iyer'), ('Rajesh Kumar', 'Rajesh Kumar'), ('Kavita Shah', 'Kavita Shah'), ('Vikrant Chauhan', 'Vikrant Chauhan'), ('Shruti Mishra', 'Shruti Mishra'), ('Deepak Yadav', 'Deepak Yadav'), ('Sonia Thakur', 'Sonia Thakur'), ('Harsh Vohra', 'Harsh Vohra'), ('Meera Saxena', 'Meera Saxena'), ('Nikhil Bansal', 'Nikhil Bansal'), ('Tanvi Agarwal', 'Tanvi Agarwal'), ('Rahul Pandey', 'Rahul Pandey'), ('Aisha Qureshi', 'Aisha Qureshi'), ('Siddharth Bose', 'Siddharth Bose'), ('Lakshmi Rao', 'Lakshmi Rao'), ('Aditya Jain', 'Aditya Jain'), ('Zoya Hussain', 'Zoya Hussain')], default='Aarav Sharma', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid to person1', 'Paid to Person1'), ('paid to person2', 'Paid to Person2')], max_length=20),
        ),
    ]
