# Generated by Django 5.2.3 on 2025-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_name_payment_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid to person1', 'Paid to Nanu'), ('paid to person2', 'Paid to Lala')], default='unpaid', max_length=20),
        ),
    ]
